
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GoruntuluGorusmeBitirme.Database
{

using System;
    using System.Collections.Generic;
    
public partial class ACCOUNT
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ACCOUNT()
    {

        this.MESSAGE = new HashSet<MESSAGE>();

        this.MESSAGE1 = new HashSet<MESSAGE>();

        this.CHAT_LOG = new HashSet<CHAT_LOG>();

        this.CHAT_LOG1 = new HashSet<CHAT_LOG>();

    }


    public int USER_ID { get; set; }

    public string NAME_SURNAME { get; set; }

    public string EMAIL { get; set; }

    public string PASS { get; set; }

    public string IMAGE { get; set; }

    public string HUB_ID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MESSAGE> MESSAGE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MESSAGE> MESSAGE1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHAT_LOG> CHAT_LOG { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHAT_LOG> CHAT_LOG1 { get; set; }

}

}
