
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GoruntuluGorusmeBitirme.Database
{

using System;
    using System.Collections.Generic;
    
public partial class CHAT_LOG
{

    public int CHAT_ID { get; set; }

    public Nullable<int> SENDER_ID { get; set; }

    public Nullable<int> RECEIVER_ID { get; set; }

    public string MESSAGE_CONTENT { get; set; }

    public Nullable<System.DateTime> SENT_TIME { get; set; }



    public virtual ACCOUNT ACCOUNT { get; set; }

    public virtual ACCOUNT ACCOUNT1 { get; set; }

}

}
