
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GoruntuluGorusmeBitirme.Database
{

using System;
    using System.Collections.Generic;
    
public partial class MESSAGE
{

    public int MESSAGE_ID { get; set; }

    public Nullable<int> MESSAGE_SENDER { get; set; }

    public Nullable<int> MESSAGE_RECEIVER { get; set; }

    public string MESSAGE_CONTENT { get; set; }

    public Nullable<System.DateTime> MESSAGE_DATE { get; set; }



    public virtual ACCOUNT ACCOUNT { get; set; }

    public virtual ACCOUNT ACCOUNT1 { get; set; }

}

}
